print(2+3)
print(3-1)
print(2*5)
print(3%4)
print(3/2)
print(2**3)
print(3//2)

print(type('Jesus Ernesto Navarro Guel'))
print(type('Mercedes Guel Cruz y Jose de Jesus Navarro Guel'))
print(type('Mexico'))
print(type('Im enjoying 30 days of python'))
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh','python','Finland']))
print(type('Jesus Ernesto Navarro Guel'))
print(type('Mercedes Guel Cruz y Jose de Jesus Navarro Guel'))
print(type('Mexico'))
print(type('Im enjoying 30 days of python'))

#Dia dos
Primer_nombre = input('¿Cual es tu primer nombre? ')
print (Primer_nombre)
